"""fix bugs with constraint

Revision ID: 3fe872119bbb
Revises: a911b5bc9c15
Create Date: 2026-02-01 15:45:32.736389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe872119bbb'
down_revision: Union[str, Sequence[str], None] = 'a911b5bc9c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('friendships_addressee_id_fkey'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('friendships_requester_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key('fk_friendships_addressee', 'friendships', 'users', ['addressee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_friendships_requester', 'friendships', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_friendships_requester', 'friendships', type_='foreignkey')
    op.drop_constraint('fk_friendships_addressee', 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_requester_id_fkey'), 'friendships', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(op.f('friendships_addressee_id_fkey'), 'friendships', 'users', ['addressee_id'], ['id'])
    # ### end Alembic commands ###
