"""cascade delete for friendship

Revision ID: 841d14c28ca6
Revises: caf7521b97fc
Create Date: 2026-02-01 15:32:27.730825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841d14c28ca6'
down_revision: Union[str, Sequence[str], None] = 'caf7521b97fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('friendships_addressee_id_fkey'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('friendships_requester_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['requester_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'friendships', 'users', ['addressee_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_requester_id_fkey'), 'friendships', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(op.f('friendships_addressee_id_fkey'), 'friendships', 'users', ['addressee_id'], ['id'])
    # ### end Alembic commands ###
