"""fixed bug

Revision ID: 96f987ddfa10
Revises: 3fe872119bbb
Create Date: 2026-02-01 15:48:18.565239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f987ddfa10'
down_revision: Union[str, Sequence[str], None] = '3fe872119bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_friendships_addressee'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('fk_friendships_requester'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['addressee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('fk_friendships_requester'), 'friendships', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_friendships_addressee'), 'friendships', 'users', ['addressee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
